# Configuración del servidor
server.port=${PORT:8081}

# Configuración de la aplicación
spring.application.name=microservicio-predictivo

# Logging
logging.level.com.tesis=DEBUG
logging.level.org.springframework.web=INFO